var MegaChips = [
  {
	"Name": "Roll",
	"Element": "Null",
	"MB": "20 MB",
	"ATK": "20",
	"Codes": "R *",
	"Description": "Attacks enmy, then heals you",
	"Image": "https://vignette1.wikia.nocookie.net/megaman/images/6/65/BN6MChip001.png",
	"MoreDetails": "",
  },
  {
	"Name": "Roll2",
	"Element": "Null",
	"MB": "40 MB",
	"ATK": "40",
	"Codes": "R",
	"Description": "Attacks enmy, then heals you",
	"Image": "https://vignette2.wikia.nocookie.net/megaman/images/4/48/BN6MChip002.png",
	"MoreDetails": "",
  },
  {
	"Name": "Roll3",
	"Element": "Null",
	"MB": "60 MB",
	"ATK": "60",
	"Codes": "R",
	"Description": "Attacks enmy, then heals you",
	"Image": "https://vignette2.wikia.nocookie.net/megaman/images/e/e5/BN6MChip003.png",
	"MoreDetails": "",
  },
  {
	"Name": "ProtoMan",
	"Element": "Sword",
	"MB": "41",
	"ATK": "150",
	"Codes": "B *",
	"Description": "Move in and slice the enemy.",
	"Image": "https://vignette4.wikia.nocookie.net/megaman/images/7/7a/BN6MChip004.png",
	"MoreDetails": "",
  },
  {
	"Name": "ProtoManEX",
	"Element": "Sword",
	"MB": "53",
	"ATK": "170",
	"Codes": "B",
	"Description": "Move in and slice the enemy.",
	"Image": "https://vignette4.wikia.nocookie.net/megaman/images/6/60/BN6MChip005.png",
	"MoreDetails": "",
  },
  {
	"Name": "ProtoManSP",
	"Element": "Sword",
	"MB": "68 MB",
	"ATK": "290",
	"Codes": "B",
	"Description": "Move in and slice the enemy.",
	"Image": "https://vignette2.wikia.nocookie.net/megaman/images/1/19/BN6MChip006.png",
	"MoreDetails": "",
  },
  {
	"Name": "SpoutMan",
	"Element": "Aqua",
	"MB": "42 MB",
	"ATK": "50",
	"Codes": "A *",
	"Description": "Watr atk! Bhnd 2row power-up",
	"Image": "https://vignette3.wikia.nocookie.net/megaman/images/4/41/BN6FMChip007.png",
	"MoreDetails": "",
  },
  {
	"Name": "SpoutMnEX",
	"Element": "Aqua",
	"MB": "56 MB",
	"ATK": "60",
	"Codes": "A",
	"Description": "Watr atk! Bhnd 2row power-up",
	"Image": "https://vignette3.wikia.nocookie.net/megaman/images/1/17/BN6FMChip008.png",
	"MoreDetails": "",
  },
  {
	"Name": "SpoutMnSP",
	"Element": "Aqua",
	"MB": "78 MB",
	"ATK": "120",
	"Codes": "A",
	"Description": "Watr atk! Bhnd 2row power-up",
	"Image": "https://vignette2.wikia.nocookie.net/megaman/images/c/c7/BN6FMChip009.png",
	"MoreDetails": "",
  },
  {
	"Name": "TmhkMan",
	"Element": "Wood",
	"MB": "40 MB",
	"ATK": "140",
	"Codes": "T *",
	"Description": "Slice 2sq side, 3sq vertical",
	"Image": "https://vignette2.wikia.nocookie.net/megaman/images/2/27/BN6FMChip010.png",
	"MoreDetails": "",
  },
  {
	"Name": "TmhkManEX",
	"Element": "Wood",
	"MB": "60 MB",
	"ATK": "160",
	"Codes": "T",
	"Description": "Slice 2sq side, 3sq vertical",
	"Image": "https://vignette1.wikia.nocookie.net/megaman/images/8/80/BN6FMChip011.png",
	"MoreDetails": "",
  },
  {
	"Name": "TmhkManSP",
	"Element": "Wood",
	"MB": "80 MB",
	"ATK": "280",
	"Codes": "T",
	"Description": "Slice 2sq side, 3sq vertical",
	"Image": "https://vignette1.wikia.nocookie.net/megaman/images/7/7c/BN6FMChip012.png",
	"MoreDetails": "",
  },
  {
	"Name": "TenguMan",
	"Element": "Wind",
	"MB": "43 MB",
	"ATK": "70",
	"Codes": "T *",
	"Description": "Attk 2row from air, then side",
	"Image": "https://vignette4.wikia.nocookie.net/megaman/images/8/83/BN6FMChip013.png",
	"MoreDetails": "",
  },
  {
	"Name": "TenguMnEX",
	"Element": "Wind",
	"MB": "61 MB",
	"ATK": "90",
	"Codes": "T",
	"Description": "Attk 2row from air, then side",
	"Image": "https://vignette1.wikia.nocookie.net/megaman/images/b/b3/BN6FMChip014.png",
	"MoreDetails": "",
  },
  {
	"Name": "TenguMnSP",
	"Element": "Wind",
	"MB": "74 MB",
	"ATK": "160",
	"Codes": "T",
	"Description": "Attk 2row from air, then side",
	"Image": "https://vignette3.wikia.nocookie.net/megaman/images/f/fe/BN6FMChip015.png",
	"MoreDetails": "",
  },
  {
	"Name": "GrndMan",
	"Element": "Break",
	"MB": "41 MB",
	"ATK": "60",
	"Codes": "G *",
	"Description": "Move fwrd then attk w/ drill",
	"Image": "https://vignette4.wikia.nocookie.net/megaman/images/e/ef/BN6FMChip016.png",
	"MoreDetails": "",
  },
  {
	"Name": "GrndManEX",
	"Element": "Break",
	"MB": "66 MB",
	"ATK": "70",
	"Codes": "G",
	"Description": "Move fwrd then attk w/ drill",
	"Image": "https://vignette4.wikia.nocookie.net/megaman/images/2/2d/BN6FMChip017.png",
	"MoreDetails": "",
  },
  {
	"Name": "GrndManSP",
	"Element": "Break",
	"MB": "85 MB",
	"ATK": "130",
	"Codes": "G",
	"Description": "Move fwrd then attk w/ drill",
	"Image": "https://vignette1.wikia.nocookie.net/megaman/images/a/a0/BN6FMChip018.png",
	"MoreDetails": "",
  },
  {
	"Name": "DustMan",
	"Element": "Null",
	"MB": "39 MB",
	"ATK": "110",
	"Codes": "D *",
	"Description": "Attk ahd. Suck in and shoot out",
	"Image": "https://vignette4.wikia.nocookie.net/megaman/images/0/0b/BN6FMChip019.png",
	"MoreDetails": "",
  },
  {
	"Name": "DustManEX",
	"Element": "Null",
	"MB": "56 MB",
	"ATK": "130",
	"Codes": "D",
	"Description": "Attk ahd. Suck in and shoot out",
	"Image": "https://vignette3.wikia.nocookie.net/megaman/images/8/8f/BN6FMChip020.png",
	"MoreDetails": "",
  },
  {
	"Name": "DustManSP",
	"Element": "Null",
	"MB": "74 MB",
	"ATK": "200",
	"Codes": "D",
	"Description": "Attk ahd. Suck in and shoot out",
	"Image": "https://vignette3.wikia.nocookie.net/megaman/images/1/14/BN6FMChip021.png",
	"MoreDetails": "",
  },
  {
	"Name": "HeatMan",
	"Element": "Fire",
	"MB": "32 MB",
	"ATK": "100",
	"Codes": "H *",
	"Description": "Burn with a radial fire attk",
	"Image": "https://vignette2.wikia.nocookie.net/megaman/images/3/3c/BN6GMChip007.png",
	"MoreDetails": "",
  },
  {
	"Name": "HeatManEX",
	"Element": "Fire",
	"MB": "55 MB",
	"ATK": "130",
	"Codes": "H",
	"Description": "Burn with a radial fire attk",
	"Image": "https://vignette4.wikia.nocookie.net/megaman/images/3/3c/BN6GMChip008.png",
	"MoreDetails": "",
  },
  {
	"Name": "HeatManSP",
	"Element": "Fire",
	"MB": "70 MB",
	"ATK": "260",
	"Codes": "H",
	"Description": "Burn with a radial fire attk",
	"Image": "https://vignette2.wikia.nocookie.net/megaman/images/f/fe/BN6GMChip009.png",
	"MoreDetails": "",
  },
  {
	"Name": "ElecMan",
	"Element": "Elec",
	"MB": "38 MB",
	"ATK": "120",
	"Codes": "E *",
	"Description": "Attk your surrndns with thdr",
	"Image": "https://vignette4.wikia.nocookie.net/megaman/images/f/f0/BN6GMChip010.png",
	"MoreDetails": "",
  },
  {
	"Name": "ElecManEX",
	"Element": "Elec",
	"MB": "52 MB",
	"ATK": "140",
	"Codes": "E",
	"Description": "Attk your surrndns with thdr",
	"Image": "https://vignette3.wikia.nocookie.net/megaman/images/b/b8/BN6GMChip011.png",
	"MoreDetails": "",
  },
  {
	"Name": "ElecManSP",
	"Element": "Elec",
	"MB": "79 MB",
	"ATK": "210",
	"Codes": "E",
	"Description": "Attk your surrndns with thdr",
	"Image": "https://vignette4.wikia.nocookie.net/megaman/images/4/46/BN6GMChip012.png",
	"MoreDetails": "",
  },
  {
	"Name": "SlashMan",
	"Element": "Sword",
	"MB": "42 MB",
	"ATK": "80",
	"Codes": "S *",
	"Description": "Slash an enmy w/ flyn knfe",
	"Image": "https://vignette4.wikia.nocookie.net/megaman/images/0/0f/BN6GMChip013.png",
	"MoreDetails": "",
  },
  {
	"Name": "SlashMnEX",
	"Element": "Sword",
	"MB": "65 MB",
	"ATK": "100",
	"Codes": "S",
	"Description": "Slash an enmy w/ flyn knfe",
	"Image": "https://vignette2.wikia.nocookie.net/megaman/images/8/87/BN6GMChip014.png",
	"MoreDetails": "",
  },
  {
	"Name": "SlashMnSP",
	"Element": "Sword",
	"MB": "79 MB",
	"ATK": "220",
	"Codes": "S",
	"Description": "Slash an enmy w/ flyn knfe",
	"Image": "https://vignette4.wikia.nocookie.net/megaman/images/0/05/BN6GMChip015.png",
	"MoreDetails": "",
  },
  {
	"Name": "EraseMan",
	"Element": "Cursor",
	"MB": "51 MB",
	"ATK": "120",
	"Codes": "K *",
	"Description": "Press (A) for 3panl beam attk",
	"Image": "https://vignette3.wikia.nocookie.net/megaman/images/8/8b/BN6GMChip016.png",
	"MoreDetails": "",
  },
  {
	"Name": "EraseMnEX",
	"Element": "Cursor",
	"MB": "65 MB",
	"ATK": "140",
	"Codes": "K",
	"Description": "Press (A) for 3panl beam attk",
	"Image": "https://vignette1.wikia.nocookie.net/megaman/images/1/1f/BN6GMChip017.png",
	"MoreDetails": "",
  },
  {
	"Name": "EraseMnSP",
	"Element": "Cursor",
	"MB": "79 MB",
	"ATK": "210",
	"Codes": "K",
	"Description": "Press (A) for 3panl beam attk",
	"Image": "https://vignette1.wikia.nocookie.net/megaman/images/c/c8/BN6GMChip018.png",
	"MoreDetails": "",
  },
  {
	"Name": "ChrgeMan",
	"Element": "Null",
	"MB": "42",
	"ATK": "60",
	"Codes": "C *",
	"Description": "Rush fwd! Open panl hit TrCar",
	"Image": "https://vignette2.wikia.nocookie.net/megaman/images/6/6e/BN6GMChip019.png",
	"MoreDetails": "",
  },
  {
	"Name": "ChrgeMnEX",
	"Element": "Null",
	"MB": "63 MB",
	"ATK": "70",
	"Codes": "C",
	"Description": "Rush fwd! Open panl hit TrCar",
	"Image": "https://vignette4.wikia.nocookie.net/megaman/images/d/d1/BN6GMChip020.png",
	"MoreDetails": "",
  },
  {
	"Name": "ChrgeMnSP",
	"Element": "Null",
	"MB": "81 MB",
	"ATK": "130",
	"Codes": "C",
	"Description": "Rush fwd! Open panl hit TrCar",
	"Image": "https://vignette3.wikia.nocookie.net/megaman/images/5/56/BN6GMChip021.png",
	"MoreDetails": "",
  },
  {
	"Name": "BlastMan",
	"Element": "Fire",
	"MB": "30 MB",
	"ATK": "120",
	"Codes": "B *",
	"Description": "Head fwd and launch blst attk",
	"Image": "https://vignette4.wikia.nocookie.net/megaman/images/e/e6/BN6MChip022.png",
	"MoreDetails": "",
  },
  {
	"Name": "BlastMnEX",
	"Element": "Fire",
	"MB": "49 MB",
	"ATK": "140",
	"Codes": "B",
	"Description": "Head fwd and launch blst attk",
	"Image": "https://vignette4.wikia.nocookie.net/megaman/images/0/0d/BN6MChip023.png",
	"MoreDetails": "",
  },
  {
	"Name": "BlastMnSP",
	"Element": "Fire",
	"MB": "68 MB",
	"ATK": "250",
	"Codes": "B",
	"Description": "Head fwd and launch blst attk",
	"Image": "https://vignette3.wikia.nocookie.net/megaman/images/9/9c/BN6MChip024.png",
	"MoreDetails": "",
  },
  {
	"Name": "DiveMan",
	"Element": "Aqua",
	"MB": "45 MB",
	"ATK": "130",
	"Codes": "D *",
	"Description": "Snd giant wave acrs area 2pnl",
	"Image": "https://vignette1.wikia.nocookie.net/megaman/images/e/e0/BN6MChip025.png",
	"MoreDetails": "",
  },
  {
	"Name": "DiveManEX",
	"Element": "Aqua",
	"MB": "60 MB",
	"ATK": "150",
	"Codes": "D",
	"Description": "Snd giant wave acrs area 2pnl",
	"Image": "https://vignette3.wikia.nocookie.net/megaman/images/c/cc/BN6MChip026.png",
	"MoreDetails": "",
  },
  {
	"Name": "DiveManSP",
	"Element": "Aqua",
	"MB": "75 MB",
	"ATK": "270",
	"Codes": "D",
	"Description": "Snd giant wave acrs area 2pnl",
	"Image": "https://vignette4.wikia.nocookie.net/megaman/images/a/a6/BN6MChip027.png",
	"MoreDetails": "",
  },
  {
	"Name": "CrcusMan",
	"Element": "Null",
	"MB": "42 MB",
	"ATK": "20",
	"Codes": "C *",
	"Description": "Capture enmy in a ash attck",
	"Image": "https://vignette3.wikia.nocookie.net/megaman/images/6/6a/BN6MChip028.png",
	"MoreDetails": "",
  },
  {
	"Name": "CrcusMnEX",
	"Element": "Null",
	"MB": "64 MB",
	"ATK": "25",
	"Codes": "C",
	"Description": "Capture enmy in a ash attck",
	"Image": "https://vignette2.wikia.nocookie.net/megaman/images/5/54/BN6MChip029.png",
	"MoreDetails": "",
  },
  {
	"Name": "CrcusMnSP",
	"Element": "Null",
	"MB": "86 MB",
	"ATK": "55",
	"Codes": "C",
	"Description": "Capture enmy in a ash attck",
	"Image": "https://vignette3.wikia.nocookie.net/megaman/images/6/67/BN6MChip030.png",
	"MoreDetails": "",
  },
  {
	"Name": "JudgeMan",
	"Element": "Elec",
	"MB": "52 MB",
	"ATK": "100",
	"Codes": "J *",
	"Description": "Whip 3 panels forward",
	"Image": "https://vignette4.wikia.nocookie.net/megaman/images/1/10/BN6MChip031.png",
	"MoreDetails": "",
  },
  {
	"Name": "JudgeMnEX",
	"Element": "Elec",
	"MB": "62 MB",
	"ATK": "120",
	"Codes": "J",
	"Description": "Whip 3 panels forward",
	"Image": "https://vignette4.wikia.nocookie.net/megaman/images/8/89/BN6MChip032.png",
	"MoreDetails": "",
  },
  {
	"Name": "JudgeMnSP",
	"Element": "Elec",
	"MB": "72 MB",
	"ATK": "190",
	"Codes": "J",
	"Description": "Whip 3 panels forward",
	"Image": "https://vignette4.wikia.nocookie.net/megaman/images/f/f3/BN6MChip033.png",
	"MoreDetails": "",
  },
  {
	"Name": "ElmntMan",
	"Element": "Null",
	"MB": "50 MB",
	"ATK": "100",
	"Codes": "E *",
	"Description": "Hit (A) whn col chges elem attk",
	"Image": "https://vignette1.wikia.nocookie.net/megaman/images/8/83/BN6MChip034.png",
	"MoreDetails": "",
  },
  {
	"Name": "ElmntMnEX",
	"Element": "Null",
	"MB": "53 MB",
	"ATK": "120",
	"Codes": "E",
	"Description": "Hit (A) whn col chges elem attk",
	"Image": "https://vignette1.wikia.nocookie.net/megaman/images/5/54/BN6MChip035.png",
	"MoreDetails": "",
  },
  {
	"Name": "ElmntMnSP",
	"Element": "Null",
	"MB": "66 MB",
	"ATK": "240",
	"Codes": "E",
	"Description": "Hit (A) whn col chges elem attk",
	"Image": "https://vignette2.wikia.nocookie.net/megaman/images/1/18/BN6MChip036.png",
	"MoreDetails": "",
  },
  {
	"Name": "Colonel",
	"Element": "Sword",
	"MB": "45 MB",
	"ATK": "160",
	"Codes": "C *",
	"Description": "Cut enmy lines in Z shape",
	"Image": "https://vignette2.wikia.nocookie.net/megaman/images/e/ee/BN6MChip037.png",
	"MoreDetails": "",
  },
  {
	"Name": "ColonelEX",
	"Element": "Sword",
	"MB": "70 MB",
	"ATK": "180",
	"Codes": "C",
	"Description": "Cut enmy lines in Z shape",
	"Image": "https://vignette3.wikia.nocookie.net/megaman/images/0/0b/BN6MChip038.png",
	"MoreDetails": "",
  },
  {
	"Name": "ColonelSP",
	"Element": "Sword",
	"MB": "91 MB",
	"ATK": "300",
	"Codes": "C",
	"Description": "Cut enmy lines in Z shape",
	"Image": "https://vignette3.wikia.nocookie.net/megaman/images/4/49/BN6MChip039.png",
	"MoreDetails": "",
  },
  {
	"Name": "Count",
	"Element": "Null",
	"MB": "60 MB",
	"ATK": "20",
	"Codes": "H *",
	"Description": "EXE6 Only. Rain on enmy then lance atk",
	"Image": "https://vignette4.wikia.nocookie.net/megaman/images/b/b8/BN6MJChip040.png",
	"MoreDetails": "",
  },
  {
	"Name": "CountEX",
	"Element": "Null",
	"MB": "75 MB",
	"ATK": "25",
	"Codes": "H",
	"Description": "EXE6 Only. Rain on enmy then lance atk",
	"Image": "https://vignette1.wikia.nocookie.net/megaman/images/a/a8/BN6MJChip041.png",
	"MoreDetails": "",
  },
  {
	"Name": "CountSP",
	"Element": "Null",
	"MB": "89 MB",
	"ATK": "50",
	"Codes": "H",
	"Description": "EXE6 Only. Rain on enmy then lance atk",
	"Image": "https://vignette4.wikia.nocookie.net/megaman/images/2/2a/BN6MJChip042.png",
	"MoreDetails": "",
  },
  {
	"Name": "Django",
	"Element": "Null",
	"MB": "30 MB",
	"ATK": "130",
	"Codes": "D *",
	"Description": "EXE6 Only. Hit enmy with bike rdng Djgo",
	"Image": "https://vignette1.wikia.nocookie.net/megaman/images/e/eb/BN6MJChip043.png",
	"MoreDetails": "",
  },
  {
	"Name": "Django2",
	"Element": "Null",
	"MB": "70 MB",
	"ATK": "180",
	"Codes": "D",
	"Description": "EXE6 Only. Hit enmy with bike rdng Djgo",
	"Image": "https://vignette1.wikia.nocookie.net/megaman/images/5/55/BN6MJChip044.png",
	"MoreDetails": "",
  },
  {
	"Name": "Django3",
	"Element": "Null",
	"MB": "90 MB",
	"ATK": "260",
	"Codes": "D",
	"Description": "EXE6 Only. Hit enmy with bike rdng Djgo",
	"Image": "https://vignette3.wikia.nocookie.net/megaman/images/b/b1/BN6MJChip045.png",
	"MoreDetails": "",
  },
  {
	"Name": "DblBeast",
	"Element": "Null",
	"MB": "99 MB",
	"ATK": "320",
	"Codes": "W",
	"Description": "EXE6 Only. Fang and wing doubl atk frenzy! ",
	"Image": "https://vignette3.wikia.nocookie.net/megaman/images/9/9a/BN6GJ_DoubleBeast.png",
	"MoreDetails": "",
  }
]